/*** Generated with $ node compileViews.js  ***  DON'T EDIT MANUALLY !!! ***/

export default {
  "inc/navbar.html": "<a href=\"\" data-dd-href=\"/\">HOME</a> | <a href=\"\" data-dd-href=\"/controller-hooks\">Controller Hooks</a> | <a href=\"\" data-dd-href=\"/model\">Model</a> | <a href=\"\" data-dd-href=\"/view-ddinc\">View#ddInc()</a> | <a href=\"\" data-dd-href=\"/view-loadviews\">View#loadViews()</a> | <a href=\"\" data-dd-href=\"/view-lazyjs\">View#lazyJS()</a> | <a href=\"\" data-dd-href=\"/datadd\">DataDd</a> | <a href=\"\" data-dd-href=\"/dataddlisteners\">DataDdListeners</a> | <a href=\"\" data-dd-href=\"/cookie\">Cookie</a> | <a href=\"\" data-dd-href=\"/browserstorage\">BrowserStorage</a> | <a href=\"\" data-dd-href=\"/form\">Form</a> | <a href=\"\" data-dd-href=\"/auth\">Auth</a> | <a href=\"\" data-dd-href=\"/navig\">navig</a> | <a href=\"\" data-dd-href=\"/paginator\">Paginator</a> | <a href=\"\" data-dd-href=\"/antiflick\">Antiflick</a> | <a href=\"\" data-dd-href=\"/i18n\">I18n</a> |",
  "pages/home/main.html": "<h1 style=\"margin-top:80px;font-size:55px;\">DoDo Framework Examples</h1><p style=\"text-align:center;font-size: larger;\"><i>Learn DoDo Framework through examples</i></p><p style=\"margin-top:50px;\"><ul><li><a href=\"/controller-hooks\" data-dd-href>Controller Lifecycle Hooks</a> - shows in which order will be executed constructor, loader, init, postrender, destroy</li><li><a href=\"/model\" data-dd-href>Model</a> - how to use model, a reactive variable designed with the <a href=\"https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy\" target=\"_blank\">Proxy Object</a></li><li><a href=\"/view-ddinc\" data-dd-href>View::ddInc()</a> - test the ddInc() method i.e. <b>data-dd-inc</b> attribute</li><li><a href=\"/view-loadviews\" data-dd-href>View::loadViews()</a> - test the loadViews() method with isAsync argument, i.e. <b>data-dd-view</b> attribute</li><li><a href=\"/view-lazyjs\" data-dd-href>View::lazyJS()</a> - load/unload JS file lazily</li><li><a href=\"/datadd\" data-dd-href>DataDd</a> - test elements with <b>data-dd-</b> attribute related to DataDd methods</li><li><a href=\"/dataddlisteners\" data-dd-href>DataDdListeners</a> - test the <b>data-dd-</b> elements related to DataDdListeners methods</li><li><a href=\"/cookie\" data-dd-href>Cookie</a> - test all Cookie methods: put, putObject, getAll, ...</li><li><a href=\"/browserstorage\" data-dd-href>BrowserStorage</a> - test localStorage &amp; sessionStorage</li><li><a href=\"/form\" data-dd-href>Form</a> - test all Form methods: setControl, getControl, delControl ...</li><li><a href=\"/login\" data-dd-href>Auth</a> - test login, logout, ... i.e. authentication methods</li><li><a href=\"/navig1\" data-dd-href>navig</a> - test Navig (navigation) methods</li><li><a href=\"/paginator\" data-dd-href>Paginator</a> - test pagination methods</li><li><a href=\"/antiflick\" data-dd-href>antiflick</a> - hide elements before the page is displayed, prevent flickering</li><li><a href=\"/i18n\" data-dd-href>i18n</a> - test internationalization i.e. automatic translation to different languages</li></ul></p>",
  "pages/notfound/main.html": "<h2 class=\"notfound\">Error 404 Not Found</h2>",
  "inc/layout.html": "<nav data-dd-inc=\"navbar.html\"></nav><main data-dd-view=\"#main\"></main>",
  "pages/controller-hooks/main.html": "<h1>Controller Lifecycle Hooks</h1> Every time a new route is opened the controller is changed and new controller lifecycle starts. <br>This example shows in which order will be executed controller constructor and the lifecycle hooks. Open the browser console to see the constructor and hook arguments. <ol><li><b>constructor(app)</b> - Will be executed on the browser page reload.</li><li><b>loader(trx)</b> - Load views via data-rg-inc and/or data-rg-view.</li><li><b>init(trx)</b> - The place where AJAX calls should be used.</li><li>rend(trx) - This method shouldn't be used unless you want to improve the app speed.</li><li><b>postrend(trx)</b> - Render HTML elements after AJAX and render are done.</li><li><b>destroy(trx)</b> - Activated when the route is changed i.e. address in the browser bar.</li></ol><br><i>app</i> is the App class instance <br><i>trx</i> is the regoch router transitional variable. <br><br><h3>A) Open another uri i.e. controller</h3><a href=\"/\" data-dd-href>HOME</a><br>- open \"HomeCtrl\" controller <br>- execute the destroy() method in the \"ControllerHooksCtrl\" controller <br><br><h3>B) Open another uri but same controller</h3><a href=\"/controller-hooks-same\" data-dd-href>/controller-hooks-same</a><br>- open \"ControllerHooksCtrl\" controller <br>- execute the destroy() method in the \"ControllerHooksCtrl\" controller <br><br><h3>C) Open same uri and same controller</h3><a href=\"/controller-hooks\" data-dd-href>/controller-hooks</a><br>- open \"ControllerHooksCtrl\" controller <br>- execute the destroy() method in the \"ControllerHooksCtrl\" controller",
  "pages/model/main.html": "<h1>Model Test ($model, $modeler)</h1><br><h3>test model as string</h3><button data-dd-click=\"str()\">str</button><br>$model.first_name: <span data-dd-print=\"$model.first_name\"></span><br><br><h3>test model as object</h3><button data-dd-click=\"obj()\">obj</button><br>$model.user.name: <span data-dd-print=\"$model.user.name\"></span><br>$model.user.age: <span data-dd-print=\"$model.user.age\"></span><br>$model.user.isActive: <span data-dd-print=\"$model.user.isActive\"></span><br><br><h3>test model as array</h3><button data-dd-click=\"arr()\">arr</button><br>$model.pets: <span data-dd-print=\"$model.pets\"></span><br><br><h3>test model with the 5 levels deep object</h3><button data-dd-click=\"level5()\">level5</button><br>$model.car.x.y.z.w.year: <span data-dd-print=\"$model.car.x.y.z.w.year\"></span><br>YEAR: <span data-dd-print=\"$model.yearOfCar\">data-dd-print=\"year\"</span><br><br><br><h3>model in INPUT tag</h3> Automatic render of the model. The text will be changed automatically as you type. <br><small>used data-dd-model=\"wood_type\"</small><br><input type=\"text\" data-dd-model=\"wood_type\"><span data-dd-print=\"$model.wood_type\"></span><br><br><small>used data-dd-model=\"$model.wood_type2\"</small><br><input type=\"text\" data-dd-model=\"$model.wood_type2\"><span data-dd-print=\"$model.wood_type2\"></span><br><br>Notice: Both <em>data-dd-model=\"wood_type\"</em> and <em>data-dd-model=\"$model.wood_type2\"</em> are valid. <br><br><br><h3>convert data type</h3> By default the model data type is converted. For example string \"1\" is converted to number 1. To control this use <b>@@ convertType</b> or <b>@@ convertTypeDont</b>. <br><br>Type some numbers or JSON or boolean in the fields. Open browser console. <br><input type=\"text\" data-dd-model=\"myMdl1\" placeholder=\"default\"><input type=\"text\" data-dd-model=\"myMdl2 @@ convertType\" placeholder=\"convertType\"><input type=\"text\" data-dd-model=\"myMdl3 @@ convertTypeDont\" placeholder=\"convertTypeDont\"><button data-dd-click=\"modelSeeConsole()\">See in console</button><br><br>",
  "pages/view-ddinc/main.html": "<h1>View#ddInc() - simply include views</h1><p> This example tests implementation of multilevel, nested <b>data-dd-inc</b> elements. which is rendered by <b>View.js#ddInc()</b> method. </p><br><article data-dd-inc=\"test/inc1.html\">--inc1.html--</article><br><br><span>--------------</span><section data-dd-inc=\"test/inc10.html @@ sibling @@ b\">--load inc10.html@@sibling@@b--</section><br><br><span>--------------</span><section data-dd-inc=\"test/inc3.html @@ prepend\">--load inc3.html@@prepend--</section>",
  "inc/test/inc1.html": "<p>INC 1</p><p data-dd-inc=\"test/inc2.html\">--inc2.html@@inner--</p>",
  "inc/test/inc10.html": "<span>INC 10</span><b>INC 10 bold </b>",
  "inc/test/inc2.html": "<p>INC 2</p><p data-dd-inc=\"test/inc3.html @@outer\">--inc3.html @@ outer--</p>",
  "inc/test/inc3.html": "<span>INC 3</span>",
  "pages/view-loadviews/main.html": "<h1>Page#loadViews() - dynamically load views</h1> The views can be loaded with <b>loadView()</b> or <b>loadViews()</b> methods used in controller loader() hook. <br><br> ++++++++++++++++++++++++++++++++ <div data-dd-view=\"#part1\"></div> ++++++++++++++++++++++++++++++++ <div data-dd-view=\"#part2\">This is </div> ++++++++++++++++++++++++++++++++ <div data-dd-view=\"#part3\"> prepended.</div> ++++++++++++++++++++++++++++++++ <br><br><br><br><br><div> This example tests <b>Page::loadViews(viewDefs, isAsync)</b>. <br><br><i>Notice:</i> If isAsync=false sometimes it can return the error <i style=\"color:red\">Element [data-dd-view=\"#part1\"] not found.</i>. </div>",
  "pages/view-loadviews/part1.html": "<p style=\"color:green\">This is from the part1.html. It's added as sibling element.</p>",
  "pages/view-loadviews/part2.html": "<b>appended from the part2.html.</b>",
  "pages/view-loadviews/part3.html": "<i>And this is from the part3.html</i><br><br><div><span>-------- DATA-RG-INC start ---------</span><article data-dd-inc=\"test/inc1.html\">--inc1.html--</article><span>---------- DATA-RG-INC end ----------</span></div><br>"
};